### ISSUE TITLE
Matcher request: containsSingle

### ISSUE THREAD

**Issue by srawlins** [dart-lang/matcher#104]
When you want to assert that collection `c` contains only item `item`, I don't think our current options are great:

```dart
// "containsAll" feels a little like a hack, and a little grammatically wrong.
expect(c.containsAll([item]));

// Two statements.
expect(c, hasLength(1));
expect(c, contains(item));

// Exception thrown is not helpful, if c has multiple items.
expect(c.single, equals(item));
```

I think a `containsSingle`, as in `expect(c.containsSingle(item));` is expressive, and uses a concept already exposed in Iterable (`.single`).

**Comment by srawlins** [comment]
CC @natebosch @grouma

**Comment by srawlins** [comment]
Yeah I like that grammatically. I suggested `containsSingle` because it matches Iterable's `single`, but `containsOnly`, `containsJust` reads better. Either way.

I'll send a PR for this if we like it.

**Comment by grouma** [comment]
Either sounds good to me.

**Comment by natebosch** [comment]
Does `expect(collection, [item]);` work here?

**Comment by srawlins** [comment]
Ouch, it does! I consider this... bad. E.g.

```dart
expect(Set.from([1]), [1]);
```

passes! I think this is just matcher trying to be helpful. It has all this special logic around Iterables and Strings to help make comparing them simpler, i.e. with `contains`. I find this pretty strange, and not very Dart 2.0 friendly. E.g. the above expectation passes, but this is invalid Dart code that errors at runtime:

```dart
// type 'MappedListIterable<int, int>' is not a subtype of type 'List<int>'
List<int> l = [1].map((e) => e*2);
```

**Comment by natebosch** [comment]
Yeah the magic around `Iterable` was introduced when Dart was much more dynamic than it is today.

I'm not sure if it's worth the migration pain to change it now...

**Comment by srawlins** [comment]
Introducing `containsSingle` or `containsOnly` means we don't have to _encourage_ users to write `expect(collection, [item]);` 😄 .

**Comment by kevmoo** [comment]
@srawlins – let make sure we get whatever you roll into `pkg:test` – I'm sick of seeing `matcher 0.12.3+1 (0.12.4 available)` 😄

**Comment by natebosch** [comment]
If you want to be explicit about the looseness of the types you can use `expect(collection, orderedEquals([item]));`. I think this would match the semantics of `containsOnly` as proposed already?

`containsSingle` seems to special case to me.

**Comment by natebosch** [comment]
Closing since I think `orderedEquals` and `unorderedEquals` give us the semantics we need.
