### ISSUE TITLE
Implement describeMismatch for TypeMatcher

### ISSUE THREAD

**Issue by ekupershlak** [dart-lang/matcher#145]
TypeMatcher does not define describeMismatch, and the default implementation provides no additional details. I'd like to implement describeMismatch so that it can be used in utility classes that rely on describeMismatch to provide human-readable error messages.

If this sounds reasonable, I would be happy to send a PR to make the change.

**Comment by natebosch** [comment]
I'm not aware of anything that should block this. @kevmoo - do you know of anything we should watch out for?

I'd be happy to review a PR here. We'll want to run tests inside google3 to make sure it isn't unintentionally breaking.

**Comment by kevmoo** [comment]
I think it'd be great to do this work!
