### ISSUE TITLE
0.12.0 has pretty hard breaking changes

### ISSUE THREAD

**Issue by zoechi** [dart-lang/matcher#2]
https://github.com/dart-lang/matcher/blob/14747b0658911cd55d140ba966653f9fbc915eab/CHANGELOG.md#0120

This will prevent using the testrunner for a while, at least until all packages which use one of those moved classes are available in a  fixed version.

I run into this in a project where I use shelf_auth.

Is there any way to keep them with a deprecation annotation for a while?

**Comment by zoechi** [comment]
I couldn't find the classes (for example FailureHandler) in unittest 0.12.0 either.

**Comment by nex3** [comment]
I'm shocked that anyone was using these definitions to begin with. They were only really intended for use in the glue code between `matcher` and `unittest`, not for wider consumption, which is largely why they've been removed.

How are your packages using them?

**Comment by zoechi** [comment]
It's not my package and I have no idea the classrs are used. I just run into that issue while trying testrunner with my project which has shelf_auth as a dependency. 
I created an issue in the shelf_auth bitbucket repo with a link to this issue.

**Comment by Andersmholmgren** [comment]
I use expect for precondition checking quite extensively. Moving this out of matcher is gonna cause me a lot of pain (sadpanda)

**Comment by nex3** [comment]
I'm closing this out, since there aren't any plans to put this stuff back in `matcher`.

@Andersmholmgren `expect()` throws a `TestFailure`, which doesn't really make sense for generic matching. Honestly, it doesn't do much *beyond* throwing that exception, so it would be pretty easy to write a custom version that throws an `ArgumentError` or whatever instead.

**Comment by Andersmholmgren** [comment]
I plug my in failure handler in to throw an ArgumentError already. I'll just have to port over some of the logic of `expect`

**Comment by zoechi** [comment]
The [mock package](https://pub.dartlang.org/packages/mock) runs into the same/similar problem. The source code for this package is not available.
Any plans to update this package for the new test package?

**Comment by zoechi** [comment]
I created http://dartbug.com/23106
