### ISSUE TITLE
Prepare for Dart 3

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/matcher#200]
The source currently contains several references to APIs scheduled for removal in Dart 3 ([details here](https://github.com/dart-lang/sdk/issues/49529)):

* [`CyclicInitializationError`](https://github.com/search?q=repo%3Adart-lang%2Fmatcher+CyclicInitializationError&type=code)
* [`NullThrownError`](https://github.com/search?q=repo%3Adart-lang%2Fmatcher+NullThrownError&type=code)

Can we move the min up to 3.0, and start working on a dev release version for this?

**Comment by jakemac53** [comment]
Do we want to do a dev version or stable version? If the current stable is selectable on 3.x, then users will get that version over the dev version.

**Comment by mit-mit** [comment]
I *think* that a) landing changes here in the repo, and b) publishing a new dev, should be sufficient?

Or were you saying that tests might fail with 3.0 dev as they'd still be on the stable package?

**Comment by jakemac53** [comment]
Right, we want users on 3.0 dev to pick this version up. We ended up going with a strategy where we don't depend on a dev sdk though, so the point is moot. We will just publish a stable version, with unchanged sdk deps.

Although now that I think about it maybe we should be upping the sdk constraint to <4.0.0 but that seems a bit premature to me at this juncture, and IIRC we went with a strategy where that won't be necessary anyways?

**Comment by jakemac53** [comment]
cc @natebosch

**Comment by natebosch** [comment]
Yeah I think keeping the SDK constraints where they are is best.

**Comment by mit-mit** [comment]
Looks like this was done in https://github.com/dart-lang/matcher/commit/7e6a665da079baa3e2a2046ab02e4353ee32556c and already rolled in https://github.com/dart-lang/sdk/commit/db636ba8fe1587750e5d836efa84d61557de9cb1?
