### ISSUE TITLE
Can we make `_DeepMatcher` handle records?

### ISSUE THREAD

**Issue by mdebbar** [dart-lang/matcher#223]
I would like to be able to do this:
```dart
expect(
  (123, <String>["foo"]),
  equals(
    (123, <String>["foo"]),
  ),
);
```

The above fails because the first `<String>["foo"]` is not identical to the second `<String>["foo"]`. And `_DeepMatcher` only handles iterables, but records are not iterables. It would be great if `_DeepMatcher` could handle records too.

AFAICT, there's no way to programmatically enumerate fields of an arbitrary record. So it may not be possible for `_DeepMatcher` to implement record deep matching today. But I'm filing an issue anyway in case someone has a clever solution for it.

**Comment by jakemac53** [comment]
Yeah I don't believe we can do deep equality generally. You could do some really nasty stuff relying on dynamic invocations and try/catch to support arbitrary positional fields only, but that would both be very narrow and very sketchy.

**Comment by mdebbar** [comment]
Does it make sense to request from the language team an API for enumerating record fields? (similar to JavaScript's `Object.getOwnPropertyNames()`).

**Comment by jakemac53** [comment]
The original Records proposal did have some reflective APIs but ultimately they were removed due to performance considerations. cc @munificent

**Comment by munificent** [comment]
Yeah, I don't think there's a way to implement this generally for all record shapes with the current API. I also don't think this alone would be a sufficiently compelling use case to want to add a reflective API for records.
