### ISSUE TITLE
Expose test/test_utils.dart (move to lib/src and export)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/matcher#39]
I find the `shouldPass` and `shouldFail` are useful and simple. I'd love not to copy paste.

**Comment by nex3** [comment]
What are you trying to accomplish here? `shouldPass()` just forwards to `expect()`, and `shouldFail()` doesn't do much more than `throwsA()` would.

**Comment by matanlurey** [comment]
It's a nice simple API for writing tests for matchers I think.

**Comment by nex3** [comment]
I don't think testing matchers is a very common use-case—most matcher definitions are small and constrained to a package's test directory. I'd also like to avoid exposing much of anything beyond pure matchers from this package.
