### ISSUE TITLE
Strong mode errors while pub upgrade

### ISSUE THREAD

**Issue by Aetet** [dart-lang/matcher#62]
Hi.
At our project we did not use matcher directly but we depend on it from `quiver` and `test` packages.

Recently after `pub upgrade` unit tests at our project failed, because of strong mode errors.  `pub upgrade` bring new version of matcher. Method signatures was changed at:
https://github.com/dart-lang/matcher/pull/61

Is it possible to use semver for such changes, because it can break external projects?

**Comment by nex3** [comment]
Can you give an example of code that was broken by #61?

**Comment by Aetet** [comment]
Before that there's no generic for predicate function:
```
      verify(track.fire('event_track', argThat(predicate((dynamic args) {
```
after pub up there's error:
```
severity: 'Error'
message: 'Missing type arguments for generic function 'predicate<T>'.'
source: 'dart'
```

so after pub upgrade some builds failed. Fix is trivial, but it takes some time to make it work again.

**Comment by nex3** [comment]
Sorry, I should have been clearer. Can you provide a full Dart program that only depends on `matcher` and worked before #61 and not after?

**Comment by kevmoo** [comment]
@Aetet – is this still an issue?
