### ISSUE TITLE
Add optional predicate argument to `isInstanceOf`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/matcher#65]
```dart
class isInstanceOf<T> extends Matcher {
  const isInstanceOf({bool predicate(T instance)});
}
```

Let me check the type AND validate properties on it – in a type-safe way

https://github.com/dart-lang/matcher/blob/fc06eae818c0602b6ea2b391bce613cb6654373e/lib/src/core_matchers.dart#L384

**Comment by nex3** [comment]
I think this is likely to be less readable than a plain `as` check. I also don't think `predicate()` is a great model for defining custom matcher behavior--I intend to replace or augment the top-level `predicate()` eventually, since in practice it often just looks like a series of `expect()` calls followed by `return true`.

**Comment by kevmoo** [comment]
Help me here.

I'm in a package w/ a custom Exception. I'd like to validate that
FooException is thrown and that it has exp.message == 'something'

This feels crazy painful now. Could we have an api that makes it easier?

Even something like expectException(functionOrFuture, (caughtException) {
  // let me write expect methods here or something
  expect(caughtException is ...)...
etc etc
});

**Comment by nex3** [comment]
Right now, the expected way to do this is to define a custom subclass of `Matcher` that asserts the type and whatever other information you want. This involves a lot of boilerplate, which sucks! It falls under #6, which tracks improving the API for defining new matchers.

One thing I've done in the past is something like this:

```dart
final isMyException = predicate((value) {
  expect(value, new isInstanceOf<MyException>());
  var error = value as MyException;
  expect(error.foo, hasSomeProperty);
  return true
});
```

**Comment by kevmoo** [comment]
https://github.com/dart-lang/matcher/issues/66
