### ISSUE TITLE
Dart 2 runtime failure in tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/matcher#79]
See the following failure when running tests in Dart 2

 Expected: 'MappedListIterable:[2, 4, 6, 8]'
    Actual: 'MappedListIterable<int, int>:[2, 4, 6, 8]'
     Which: is different.
            Expected: ... stIterable:[2, 4, 6, ...
              Actual: ... stIterable<int, int> ...
                                    ^
             Differ at offset 18
  
  package:test                                                                   expect
  ../../matcher/test/pretty_print_test.dart 247:7  main.<fn>.<fn>

**Comment by nex3** [comment]
I'm not maintaining `test` and `matcher` anymore.

**Comment by grouma** [comment]
I think this can be closed. @keertip can you confirm?

**Comment by natebosch** [comment]
looks like it's still a problem due to a different `toString()` representation in Dart 2.

**Comment by keertip** [comment]
Still an issue, see it fail while running tests internally.
