### ISSUE TITLE
isInstanceOf should be a method

### ISSUE THREAD

**Issue by Hixie** [dart-lang/matcher#98]
@kevmoo @natebosch 
Based on our meeting today, Flutter is hiding `TypeMatcher` and `isInstanceOf` from `test` in all our tests (and in the `flutter_test` package that we export to our users), and instead just exporting a function called `isInstanceOf`. This is ugly and we would prefer if we could just have an `isInstanceOf` method so that we didn't need to have these hacks.

**Comment by kevmoo** [comment]
When we're ready to roll a major release of matcher + test, we'll make this change!

**Comment by Hixie** [comment]
#110 didn't solve this. It used a different name that won't allow us to unfork.

**Comment by natebosch** [comment]
Will leave open until we can remove `isInstanceOf` with a breaking change version bump.

**Comment by natebosch** [comment]
Discussed offline - `flutter_test` will keep it's own `isInstanceOf` unless they decide to do a breaking change, or forever, which can be handled independently from anything test. We will not keep `isInstanceOf` in `matcher` or `test` once we have other compelling reasons for a breaking version bump.

**Comment by jamesderlin** [comment]
I'm not sure what the current intention is, but currently the documentation for `isInstanceOf` says:

> DEPRECATED Use [TypeMatcher](https://pub.dev/documentation/matcher/latest/matcher/TypeMatcher-class.html) instead.

but also:

> Annotations
>         @Deprecated('Use `isA<MyType>()` instead.')

which seems inconsistent.

**Comment by jamesderlin** [comment]
It's also confusing to recommending using `TypeMatcher` because Flutter has its [own copy of the `package:matcher` docs](https://api.flutter.dev/flutter/package-matcher_matcher/isInstanceOf-class.html), but in a Flutter context, `package:matcher`'s `TypeMatcher` is hidden and `TypeMatcher` is [something different](https://api.flutter.dev/flutter/widgets/TypeMatcher-class.html).

**Comment by kevmoo** [comment]
FYI: Flutter [TypeMatcher](https://api.flutter.dev/flutter/widgets/TypeMatcher-class.html) is now marked as deprecated.

We shipped `isA<T>`, which can be pointed to by Flutters `isInstanceOf` function.

Can we close this out?
